Use pipe to communicate with sub command.

diff --git a/examples/facade-sub-command b/examples/facade-sub-command
--- a/examples/facade-sub-command
+++ b/examples/facade-sub-command
@@ -1,3 +1,10 @@
 #!/bin/sh
-echo "sub command"
-echo "hello"
+echo $0
+echo $1
+echo $2
+echo "sub command started"
+echo "woke up"
+echo "error 1" 1>&2
+echo "error 2" 1>&2
+sleep 1
+echo "finish"
